workflows:
  ios_ipa_unsigned:
    name: iOS — Build unsigned IPA
    environment:
      flutter: stable
      xcode: 15.4
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS IPA (release)
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa