workflows:
  ios_ipa_unsigned:
    name: iOS — Unsigned IPA (no codesign)
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Ensure iOS folder exists
        script: flutter create .
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Package unsigned IPA
        script: |
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
          cd Payload
          zip -r ../Runner-unsigned.ipa .
          cd ..
    artifacts:
      - Runner-unsigned.ipa
